// Auth
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_SUCCESS1 = 'LOGIN_SUCCESS1';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT_REQUEST = "LOGOUT_REQUEST";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAILURE = "LOGOUT_FAILURE";
export const VERIFY_REQUEST = "VERIFY_REQUEST";
export const VERIFY_SUCCESS = "VERIFY_SUCCESS";
export const PASSWORD_VERIFY_REQUEST = "PASSWORD_VERIFY_REQUEST";
export const PASSWORD_VERIFY_SUCCESS = "PASSWORD_VERIFY_SUCCESS";
export const PASSWORD_VERIFY_FAILURE = "PASSWORD_VERIFY_FAILURE";
export const ACCOUNT_LINKING_REQUEST = "ACCOUNT_LINKING_REQUEST";
export const ACCOUNT_LINKING_SUCCESS = "ACCOUNT_LINKING_SUCCESS";
export const ACCOUNT_LINKING_FAILURE = "ACCOUNT_LINKING_FAILURE";
export const CHANGE_PASSWORD_REQUEST = "CHANGE_PASSWORD_REQUEST";
export const CHANGE_PASSWORD_SUCCESS = "CHANGE_PASSWORD_SUCCESS";
export const CHANGE_PASSWORD_FAILURE = "CHANGE_PASSWORD_FAILURE";
export const OTP_REQUEST = "OTP_REQUEST";
export const OTP_SUCCESS = "OTP_SUCCESS";
export const OTP_FAILURE = "OTP_FAILURE";
export const OTP_RESET = "OTP_RESET";
export const MULTIFACTOR_AUTH_OPTIONS_REQUEST = "MULTIFACTOR_AUTH_OPTIONS_REQUEST";
export const MULTIFACTOR_AUTH_OPTIONS_SUCCESS = "MULTIFACTOR_AUTH_OPTIONS_SUCCESS";
export const MULTIFACTOR_AUTH_OPTIONS_FAILURE = "MULTIFACTOR_AUTH_OPTIONS_FAILURE";
export const MULTIFACTOR_AUTH_REQUEST = "MULTIFACTOR_AUTH_REQUEST";
export const MULTIFACTOR_AUTH_SUCCESS = "MULTIFACTOR_AUTH_SUCCESS";
export const MULTIFACTOR_AUTH_FAILURE = "MULTIFACTOR_AUTH_FAILURE";
export const MFA_AUTH_REQUEST = "MFA_AUTH_REQUEST";
export const MFA_AUTH_SUCCESS = "MFA_AUTH_SUCCESS";
export const MFA_AUTH_FAILURE = "MFA_AUTH_FAILURE";
export const VERIFY_RECAPTCHA_REQUEST = "VERIFY_RECAPTCHA_REQUEST";
export const VERIFY_RECAPTCHA_SUCCESS = "VERIFY_RECAPTCHA_SUCCESS";
export const VERIFY_RECAPTCHA_FAILURE = "VERIFY_RECAPTCHA_FAILURE";
export const LOADING = "LOADING";
export const SENT_EMAIL_VERIFICATION_REQUEST = "SENT_EMAIL_VERIFICATION_REQUEST"
export const SENT_EMAIL_VERIFICATION_SUCCESS = "SENT_EMAIL_VERIFICATION_SUCCESS"
export const SENT_EMAIL_VERIFICATION_FAILURE = "SENT_EMAIL_VERIFICATION_FAILURE"
export const SEND_PASSWORD_RESET_EMAIL_REQUEST = "SEND_PASSWORD_RESET_EMAIL_REQUEST"
export const SEND_PASSWORD_RESET_EMAIL_SUCCESS = "SEND_PASSWORD_RESET_EMAIL_SUCCESS"
export const SEND_PASSWORD_RESET_EMAIL_FAILURE = "SEND_PASSWORD_RESET_EMAIL_FAILURE"
export const SEND_FORGOT_EMAIL_REQUEST = "SEND_FORGOT_EMAIL_REQUEST"
export const SEND_FORGOT_EMAIL_SUCCESS = "SEND_FORGOT_EMAIL_SUCCESS"
export const SEND_FORGOT_EMAIL_FAILURE = "SEND_FORGOT_EMAIL_FAILURE"
export const FETCH_SIGN_METHODS =      "FETCH_SIGN_METHODS";
export const GET_VISITORS_COUNT_REQUEST = "GET_VISITORS_COUNT_REQUEST";
export const GET_VISITORS_COUNT_SUCCESS = "GET_VISITORS_COUNT_SUCCESS";
export const GET_VISITORS_COUNT_FAILURE = "GET_VISITORS_COUNT_FAILURE";

export const GET_REAL_TIME_USERS_COUNT_REQUEST = "GET_REAL_TIME_USERS_COUNT_REQUEST";
export const GET_REAL_TIME_USERS_COUNT_SUCCESS = "GET_REAL_TIME_USERS_COUNT_SUCCESS";
export const GET_REAL_TIME_USERS_COUNT_FAILURE = "GET_REAL_TIME_USERS_COUNT_FAILURE";
export const ADD_USER_COUNT_REQUEST = "ADD_USER_COUNT_REQUEST";
export const ADD_USER_COUNT_SUCCESS = "ADD_USER_COUNT_SUCCESS";
export const ADD_USER_COUNT_FAILURE = "ADD_USER_COUNT_FAILURE";

export const REMOVE_USER_COUNT_REQUEST = "REMOVE_USER_COUNT_REQUEST";
export const REMOVE_USER_COUNT_SUCCESS = "REMOVE_USER_COUNT_SUCCESS";
export const REMOVE_USER_COUNT_FAILURE = "REMOVE_USER_COUNT_FAILURE";



// Google Recaptcha Status

export const GOOGLE_RECAPTCHA_REQUEST = "GOOGLE_RECAPTCHA_REQUEST";
export const GOOGLE_RECAPTCHA_SUCCESS = "GOOGLE_RECAPTCHA_SUCCESS";
export const GOOGLE_RECAPTCHA_FAILURE = "GOOGLE_RECAPTCHA_FAILURE";
export const RESET_GOOGLE_RECAPTCHA_TOKEN = "RESET_GOOGLE_RECAPTCHA_TOKEN"
// Redirect
export const REDIRECT_REQUEST = "REDIRECT_REQUEST";
export const CLEAR_REDIRECT = "CLEAR_REDIRECT";
export const REDIRECT_SUCCESS = "REDIRECT_SUCCESS";
export const REDIRECT_FAILURE = "REDIRECT_FAILURE";


// Notifications

export const NOTIFICAIONS_REQUEST = "NOTIFICAIONS_REQUEST";
export const NOTIFICAIONS_SUCCESS = "NOTIFICAIONS_SUCCESS";
export const NOTIFICAIONS_FAILURE = "NOTIFICAIONS_FAILURE";
export const NOTIFICAION_BY_ID_REQUEST = "NOTIFICAION_BY_ID_REQUEST";
export const NOTIFICAION_BY_ID_SUCCESS = "NOTIFICAION_BY_ID_SUCCESS";
export const NOTIFICAION_BY_ID_FAILURE = "NOTIFICAION_BY_ID_FAILURE";
// User
export const SET_CURRENT_USER= 'SET_CURRENT_USER';
export const CLEAR_CURRENT_USER = 'CLEAR_CURRENT_USER';


//users data for admin

export const GET_USERS_FAILURE= 'GET_USERS_FAILURE';
export const GET_USERS_REQUEST= 'GET_USERS_REQUEST';
export const GET_USERS_SUCCESS= 'GET_USERS_SUCCESS';
// export const SET_USER_DATA = "SET_USER_DATA";
export const CREATE_NEW_USER_FAILURE= 'CREATE_NEW_USER_FAILURE';
export const CREATE_NEW_USER_REQUEST= 'CREATE_NEW_USER_REQUEST';
export const CREATE_NEW_USER_SUCCESS= 'CREATE_NEW_USER_SUCCESS';
// get user metadata
export const GET_USER_METADATA_FAILURE= 'GET_USER_METADATA_FAILURE';
export const GET_USER_METADATA_REQUEST= 'GET_USER_METADATA_REQUEST';
export const GET_USER_METADATA_SUCCESS= 'GET_USER_METADATA_SUCCESS';

// user data
export const GET_USER_DATA_FAILURE= 'GET_USER_DATA_FAILURE';
export const GET_USER_DATA_REQUEST= 'GET_USER_DATA_REQUEST';
export const GET_USER_DATA_SUCCESS= 'GET_USER_DATA_SUCCESS';
export const GET_CURRENT_USER_DATA_FAILURE= 'GET_CURRENT_USER_DATA_FAILURE';
export const GET_CURRENT_USER_DATA_REQUEST= 'GET_CURRENT_USER_DATA_REQUEST';
export const GET_CURRENT_USER_DATA_SUCCESS= 'GET_CURRENT_USER_DATA_SUCCESS';
export const UPDATE_USER_DATA_FAILURE= 'UPDATE_USER_DATA_FAILURE';
export const UPDATE_USER_DATA_REQUEST= 'UPDATE_USER_DATA_REQUEST';
export const UPDATE_USER_DATA_SUCCESS= 'UPDATE_USER_DATA_SUCCESS';
export const GET_USER_DATA_BY_USERNAME_FAILURE= 'GET_USER_DATA_BY_USERNAME_FAILURE';
export const GET_USER_DATA_BY_USERNAME_REQUEST= 'GET_USER_DATA_BY_USERNAME_REQUEST';
export const GET_USER_DATA_BY_USERNAME_SUCCESS= 'GET_USER_DATA_BY_USERNAME_SUCCESS';
export const CLEAR_USER_DATA_FAILURE= 'CLEAR_USER_DATA_FAILURE';
export const CLEAR_USER_DATA_REQUEST= 'CLEAR_USER_DATA_REQUEST';
export const CLEAR_USER_DATA_SUCCESS= 'CLEAR_USER_DATA_SUCCESS';
export const EDUCATION_FAILURE= 'EDUCATION_FAILURE';
export const EDUCATION_REQUEST= 'EDUCATION_REQUEST';
export const EDUCATION_SUCCESS= 'EDUCATION_SUCCESS';
export const EXPERIENCE_FAILURE= 'EXPERIENCE_FAILURE';
export const EXPERIENCE_REQUEST= 'EXPERIENCE_REQUEST';
export const EXPERIENCE_SUCCESS= 'EXPERIENCE_SUCCESS';
export const PROFILE_UPDATE_FAILURE= 'PROFILE_UPDATE_FAILURE';
export const PROFILE_UPDATE_REQUEST= 'PROFILE_UPDATE_REQUEST';
export const PROFILE_UPDATE_SUCCESS= 'PROFILE_UPDATE_SUCCESS';





// Get in Touch form 

export const SUBMIT_GET_IN_TOUCH_FAILURE= 'SUBMIT_GET_IN_TOUCH_FAILURE';
export const SUBMIT_GET_IN_TOUCH_REQUEST= 'SUBMIT_GET_IN_TOUCH_REQUEST';
export const SUBMIT_GET_IN_TOUCH_SUCCESS= 'SUBMIT_GET_IN_TOUCH_SUCCESS';
// Subscribe us form

export const SUBMIT_SUBSCRIBE_REQUEST= 'SUBMIT_SUBSCRIBE_REQUEST';
export const SUBMIT_SUBSCRIBE_SUCCESS= 'SUBMIT_SUBSCRIBE_SUCCESS';
export const SUBMIT_SUBSCRIBE_FAILURE= 'SUBMIT_SUBSCRIBE_FAILURE';

// blogs 

export const SET_BLOG_AUTHOR = "SET_BLOG_AUTHOR";
export const TRENDING_BLOGS_REQUEST = 'TRENDING_BLOGS_REQUEST';
export const TRENDING_BLOGS_FAILURE = 'TRENDING_BLOGS_FAILURE';
export const TRENDING_BLOGS_SUCCESS = 'TRENDING_BLOGS_SUCCESS';
export const GET_TOTAL_BLOGS_REQUEST = 'GET_TOTAL_BLOGS_REQUEST';
export const GET_TOTAL_BLOGS_SUCCESS = 'GET_TOTAL_BLOGS_SUCCESS';
export const GET_TOTAL_BLOGS_FAILURE = 'GET_TOTAL_BLOGS_FAILURE';
export const GET_BLOGS_REQUEST = 'GET_BLOGS_REQUEST';
export const GET_BLOGS_SUCCESS = 'GET_BLOGS_SUCCESS';
export const GET_BLOGS_FAILURE = 'GET_BLOGS_FAILURE';
export const SEARCH_BLOGS_REQUEST = 'SEARCH_BLOGS_REQUEST';
export const SEARCH_BLOGS_SUCCESS = 'SEARCH_BLOGS_SUCCESS';
export const SEARCH_BLOGS_FAILURE = 'SEARCH_BLOGS_FAILURE';
export const SEARCH_BLOGS = 'SEARCH_BLOGS';
export const APPEND_BLOGS = 'APPEND_BLOGS';
export const BLOGS_LIMIT_SET = "BLOGS_LIMIT_SET";
export const HIDE_MORE_BUTTON = "HIDE_MORE_BUTTON";
export const GET_BLOG_DETAILS_REQUEST = 'GET_BLOG_DETAILS_REQUEST';
export const GET_BLOG_DETAILS_FAILURE = 'GET_BLOG_DETAILS_FAILURE';
export const GET_BLOG_DETAILS_SUCCESS = 'GET_BLOG_DETAILS_SUCCESS';
export const SET_TAGS_REQUEST = 'SET_TAGS_REQUEST';
export const SET_TAGS_FAILURE = 'SET_TAGS_FAILURE';
export const SET_TAGS_SUCCESS = 'SET_TAGS_SUCCESS';
export const SET_CATEGORIES_REQUEST = 'SET_CATEGORIES_REQUEST';
export const SET_CATEGORIES_FAILURE = 'SET_CATEGORIES_FAILURE';
export const SET_CATEGORIES_SUCCESS = 'SET_CATEGORIES_SUCCESS';
export const SET_COMMENTS_REQUEST = 'SET_COMMENTS_REQUEST';
export const SET_COMMENTS_FAILURE = 'SET_COMMENTS_FAILURE';
export const SET_COMMENTS_SUCCESS = 'SET_COMMENTS_SUCCESS';
export const SET_LIKES_REQUEST = 'SET_LIKES_REQUEST';
export const SET_LIKES_FAILURE = 'SET_LIKES_FAILURE';
export const SET_LIKES_SUCCESS = 'SET_LIKES_SUCCESS';
export const ADD_BLOG_REQUEST = 'ADD_BLOG_REQUEST';
export const ADD_BLOG_SUCCESS = 'ADD_BLOG_SUCCESS';
export const ADD_BLOG_FAILURE = 'ADD_BLOG_FAILURE';
export const EDIT_BLOG_REQUEST = 'EDIT_BLOG_REQUEST';
export const EDIT_BLOG_SUCCESS = 'EDIT_BLOG_SUCCESS';
export const EDIT_BLOG_FAILURE = 'EDIT_BLOG_FAILURE';
export const DELETE_BLOG_REQUEST = 'DELETE_BLOG_REQUEST';
export const DELETE_BLOG_SUCCESS = 'DELETE_BLOG_SUCCESS';
export const DELETE_BLOG_FAILURE = 'DELETE_BLOG_FAILURE';
export const ADD_DELETED_BLOG_REQUEST = 'ADD_DELETED_BLOG_REQUEST';
export const ADD_DELETED_BLOG_SUCCESS = 'ADD_DELETED_BLOG_SUCCESS';
export const ADD_DELETED_BLOG_FAILURE = 'ADD_DELETED_BLOG_FAILURE';
export const ADD_LIKE = 'ADD_LIKE';
export const REMOVE_LIKE = "REMOVE_LIKE";
export const ADD_COMMENT = 'ADD_COMMENT';
export const REMOVE_COMMENT = "REMOVE_COMMENT";
export const EDIT_COMMENT = 'EDIT_COMMENT';
export const SET_COMMENTS = "SET_COMMENTS";
export const SET_RELATED_BLOGS = "SET_RELATED_BLOGS";
export const SET_RECENT_BLOGS = "SET_RECENT_BLOGS";
export const PROFILE_IMAGE_CHANGE = "PROFILE_IMAGE_CHANGE";
export const FILE_UPLOAD_PROGRESS = "FILE_UPLOAD_PROGRESS";
export const SET_TAGS = "SET_TAGS";
export const SET_CATEGORIES = "SET_CATEGORIES";
export const GET_SENT_TO_REVIEW_TOTAL_BLOGS_REQUEST = 'GET_SENT_TO_REVIEW_TOTAL_BLOGS_REQUEST';
export const GET_SENT_TO_REVIEW_TOTAL_BLOGS_SUCCESS = 'GET_SENT_TO_REVIEW_TOTAL_BLOGS_SUCCESS';
export const GET_SENT_TO_REVIEW_TOTAL_BLOGS_FAILURE = 'GET_SENT_TO_REVIEW_TOTAL_BLOGS_FAILURE';
// export const GET_BLOG_DETAILS_REQUEST = 'GET_BLOG_DETAILS_REQUEST';

// Templates

export const GET_TEMPLATES_REQUEST = "GET_TEMPLATES_REQUEST";
export const GET_TEMPLATES_SUCCESS = "GET_TEMPLATES_SUCCESS";
export const GET_TEMPLATES_FAILURE = "GET_TEMPLATES_FAILURE";
export const GET_TEMPLATE_REQUEST = "GET_TEMPLATE_REQUEST";
export const GET_TEMPLATE_SUCCESS = "GET_TEMPLATE_SUCCESS";
export const GET_TEMPLATE_FAILURE = "GET_TEMPLATE_FAILURE";
export const ADD_TEMPLATE_REQUEST = "ADD_TEMPLATE_REQUEST";
export const ADD_TEMPLATE_SUCCESS = "ADD_TEMPLATE_SUCCESS";
export const ADD_TEMPLATE_FAILURE = "ADD_TEMPLATE_FAILURE";
export const EDIT_TEMPLATE_REQUEST = "EDIT_TEMPLATE_REQUEST";
export const EDIT_TEMPLATE_SUCCESS = "EDIT_TEMPLATE_SUCCESS";
export const EDIT_TEMPLATE_FAILURE = "EDIT_TEMPLATE_FAILURE";
export const DELETE_TEMPLATE_REQUEST = "DELETE_TEMPLATE_REQUEST";
export const DELETE_TEMPLATE_SUCCESS = "DELETE_TEMPLATE_SUCCESS";
export const DELETE_TEMPLATE_FAILURE = "DELETE_TEMPLATE_FAILURE";
export const FILE_UPLOAD_SUCCESS = "FILE_UPLOAD_SUCCESS";

// File manager 


export const SET_LOADING = "SET_LOADING";
export const SET_ADMIN_FILES = "SET_ADMIN_FILES";
export const SET_ADMIN_FOLDERS = "SET_ADMIN_FOLDERS";
export const SET_USER_FOLDERS = "SET_USER_FOLDERS";
export const SET_SHARED_FOLDERS = "SET_SHARED_FOLDERS";
export const ADD_USER_FOLDER = "ADD_USER_FOLDER";
export const RESET_FOLDERS_FILES = "RESET_FOLDERS_FILES";
export const SET_USER_FILES = "SET_USER_FILES";
export const ADD_USER_FILE = "ADD_USER_FILE";
export const UPDATE_USER_FILE_DATA = "UPDATE_USER_FILE_DATA";
export const DELETE_USER_FILE = "DELETE_USER_FILE";
export const DELETE_USER_FOLDER = "DELETE_USER_FOLDER";
export const SET_SORTED_USER_FOLDERS = "SET_SORTED_USER_FOLDERS";
export const SET_SORTED_USER_FILES = "SET_SORTED_USER_FILES";
export const SET_SORTED_USER_SHARED_FILES = "SET_SORTED_USER_SHARED_FILES";
export const SET_SORTED_USER_SHARED_FOLDERS = "SET_SORTED_USER_SHARED_FOLDERS";
// Error codes
export const ERROR_CODE_ACCOUNT_EXISTS =
  'auth/account-exists-with-different-credential';

export const ERROR_MSG_ACCOUNT_EXISTS = `
  An account with an E-Mail address to
  this social account already exists. Try to login from
  this account instead and associate your social accounts on
  your personal account page.
`;
export const ERROR_CODE_ACCOUNT_ALREADY_EXISTS = 'auth/email-already-in-use';
export const ERROR_MSG_ACCOUNT_ALREADY_EXISTS = `
An account with an E-Mail address is already exists. Try to login from
  this account instead.`;
export const ERROR_CODE_WRONG_PASSWORD = 'auth/wrong-password';
export const ERROR_MSG_WRONG_PASSWORD = `Wrong Password! \n Please try again`;
export const ERROR_CODE_TOO_MANY_ATTEMPTS = "auth/too-many-requests";
export const ERROR_MSG_TOO_MANY_ATTEMPTS = `Access to this account has been temporarily disabled due to many failed login attempts.\n You can immediately restore it by resetting your password or you can try again later.`
// messages

export const MESSAGES_REQUEST = "MESSAGES_REQUEST";
export const MESSAGES_SUCCESS = "MESSAGES_SUCCESS";
export const MESSAGES_ERROR = 'MESSAGES_ERROR';
export const MESSAGE_REQUEST = "MESSAGE_REQUEST";
export const MESSAGE_SUCCESS = "MESSAGE_SUCCESS";
export const MESSAGE_ERROR = 'MESSAGE_ERROR';
export const SEND_MESSAGE_REQUEST = 'SEND_MESSAGE_REQUEST';
export const SEND_MESSAGE_SUCCESS = 'SEND_MESSAGE_SUCCESS';
export const SEND_MESSAGE_ERROR = 'SEND_MESSAGE_ERROR';
export const MESSAGES_SET = "MESSAGES_SET";
export const MESSAGES_LIMIT_SET = "MESSAGES_LIMIT_SET";